### ISSUE TITLE
Do the text "Free" above the text "Open source on GitHub" means "gratis" or "free/opensource software" or both?

### ISSUE THREAD

**Issue by 3-E-D** [NickeManarin/ScreenToGif-Website#2]
I need to translate the text into my native language so I would like to know the meaning of this word in the context.

**Comment by NickeManarin** [comment]
It means that it's a free of charge (gratis) software with the source code available on GitHub.

So, both. :)

**Comment by 3-E-D** [comment]
Wow, thats an instant response, thanks a lot.
