### ISSUE TITLE
[question] how should I add locale

### ISSUE THREAD

**Issue by Riajyuu** [NickeManarin/ScreenToGif-Website#2]
I can't see switch button on this site. So how should I process or should I even add any?

**Comment by NickeManarin** [comment]
There's currently no "switch language" button on the website. The language is detected on load and set as parameter on the URL. Like "?l=pt"

**Comment by EMLVIRUS** [comment]
In that case, if any locale is going to be added, parameter should be all modified in all HTML.

**Comment by NickeManarin** [comment]
No, for any translation added to the website, only one part of the code should be altered:

https://github.com/NickeManarin/ScreenToGif-Website/blob/a7ba48f493eafdec7cfd3bb0ccc97bcc1728a001/js/trans.js#L9

For example, if Russian gets added, you just need to add "ru_ru" to that line and add the **ru_ru** translation inside the **function Language(lang)**.

If you PC uses Russian language, it will automatically add "**?l=ru_ru**" to the end of every URL.
